insert into categories(category_name) values ('Electronics'),
('Clothing'),
('Books'),
('Beauty Products'),
('Automobiles'),
('Video Games'),
('Home & Kitchen'),
('Toys & Games'),
('Health & Household'),
('Pet Supplies'),
('Sports & Outdoors'),
('Tools & Home Improvement'),
('Arts, Crafts & Sewing'),
('Baby'),
('Garden & Outdoor'),
('Musical Instruments'),
('Office Products'),
('Software'),
('Collectibles & Fine Art'),
('Industrial & Scientific'),
('Handmade');

insert into subcategories(category_id, subcategory_name) values ((select category_id from categories where category_name = 'Electronics'), 'Computers'),
((select category_id from categories where category_name = 'Electronics'), 'Smartphones'),
((select category_id from categories where category_name = 'Electronics'), 'Accessories'),
((select category_id from categories where category_name = 'Electronics'), 'Televisions & Home Theater'),
((select category_id from categories where category_name = 'Electronics'), 'Cameras & Photography'),
((select category_id from categories where category_name = 'Electronics'), 'Wearable Technology'),
((select category_id from categories where category_name = 'Clothing'), 'Women''s Fashion'),
((select category_id from categories where category_name = 'Clothing'), 'Men''s Fashion'),
((select category_id from categories where category_name = 'Clothing'), 'Kids'' Fashion'),
((select category_id from categories where category_name = 'Clothing'), 'Footwear'),
((select category_id from categories where category_name = 'Books'), 'Fiction'),
((select category_id from categories where category_name = 'Books'), 'Non-Fiction'),
((select category_id from categories where category_name = 'Books'), 'Children''s Books'),
((select category_id from categories where category_name = 'Beauty Products'), 'Skincare'),
((select category_id from categories where category_name = 'Beauty Products'), 'Makeup'),
((select category_id from categories where category_name = 'Beauty Products'), 'Haircare'),
((select category_id from categories where category_name = 'Automobiles'), 'Car Parts & Accessories'),
((select category_id from categories where category_name = 'Automobiles'), 'Motorcycles'),
((select category_id from categories where category_name = 'Video Games'), 'PC Games'),
((select category_id from categories where category_name = 'Video Games'), 'PlayStation Games'),
((select category_id from categories where category_name = 'Video Games'), 'Xbox Games'),
((select category_id from categories where category_name = 'Home & Kitchen'), 'Kitchen Appliances'),
((select category_id from categories where category_name = 'Home & Kitchen'), 'Home Decor'),
((select category_id from categories where category_name = 'Home & Kitchen'), 'Furniture'),
((select category_id from categories where category_name = 'Toys & Games'), 'Action Figures'),
((select category_id from categories where category_name = 'Toys & Games'), 'Board Games'),
((select category_id from categories where category_name = 'Health & Household'), 'Vitamins & Supplements'),
((select category_id from categories where category_name = 'Health & Household'), 'Household Cleaners'),
((select category_id from categories where category_name = 'Pet Supplies'), 'Dog Supplies'),
((select category_id from categories where category_name = 'Pet Supplies'), 'Cat Supplies'),
((select category_id from categories where category_name = 'Sports & Outdoors'), 'Fitness Equipment'),
((select category_id from categories where category_name = 'Sports & Outdoors'), 'Camping & Hiking'),
((select category_id from categories where category_name = 'Tools & Home Improvement'), 'Power Tools'),
((select category_id from categories where category_name = 'Tools & Home Improvement'), 'Hand Tools'),
((select category_id from categories where category_name = 'Arts, Crafts & Sewing'), 'Painting & Drawing'),
((select category_id from categories where category_name = 'Arts, Crafts & Sewing'), 'Sewing & Fabric'),
((select category_id from categories where category_name = 'Baby'), 'Diapering'),
((select category_id from categories where category_name = 'Baby'), 'Feeding'),
((select category_id from categories where category_name = 'Garden & Outdoor'), 'Gardening Tools'),
((select category_id from categories where category_name = 'Garden & Outdoor'), 'Outdoor Decor'),
((select category_id from categories where category_name = 'Musical Instruments'), 'Guitars'),
((select category_id from categories where category_name = 'Musical Instruments'), 'Keyboards'),
((select category_id from categories where category_name = 'Office Products'), 'Office Electronics'),
((select category_id from categories where category_name = 'Office Products'), 'Office Furniture'),
((select category_id from categories where category_name = 'Software'), 'Operating Systems'),
((select category_id from categories where category_name = 'Software'), 'Productivity Software'),
((select category_id from categories where category_name = 'Collectibles & Fine Art'), 'Coins & Paper Money'),
((select category_id from categories where category_name = 'Collectibles & Fine Art'), 'Stamps'),
((select category_id from categories where category_name = 'Industrial & Scientific'), 'Lab & Scientific Products'),
((select category_id from categories where category_name = 'Industrial & Scientific'), 'Safety & Security'),
((select category_id from categories where category_name = 'Handmade'), 'Handmade Jewelry'),
((select category_id from categories where category_name = 'Handmade'), 'Handmade Home Decor');

