# cspell:disable
# View results on github.com
# gh CLI commands to view results
# [list of all workflows]:
# gh run list
# [show the latest results of a specific workflow]
# gh run list --workflow=<name_of_test_file>.yml -L 1
# [Extract the run id]:
# run_id=$(gh run list --workflow=<name_of_test_file>.yml -L 1|awk -F'\t' '{print $7}') && echo $run_id
# [watch a workflow run]:
# gh run watch <run_id>
# [view details of a run]:
# gh run view <run_id>
# [view log details of a run]:
# gh run view <run_id> --log
# [view only log details]:
# gh run view <run_id> --log|awk -F'\t' '{print $3}'|awk -F'Z ' '{print $2}'
# [One line]:
# run_id=$(gh run list -L 1|awk -F'\t' '{print $7}') && gh run view $run_id --log-failed|awk -F'\t' '{print $3}'|awk -F'Z ' '{print $2}'
# [Download artifacts of a run]:
# gh run download <run_id>
# [Rerun a workflow run]:
# gh run rerun <run_id>

name: Thrift-app Testing

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: 'postgresql://postgres:postgres@127.0.0.1:54322/postgres'
      SUPABASE_ACCESS_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU'
      SERVER: http://localhost:1024
      SUPABASE_URL: http://localhost:54321
      ACTIONS_STEP_DEBUG: true
      CI: true
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}

    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 22

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: supabase start

      - name: Use Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - run: npm install -g pnpm

      - run: pnpm install

      - run: pnpm build

      - name: Start server
        run: |
          pnpm start-test &> results.log &
          sleep 5

      - name: Run tests
        run: pnpm tests

      - name: View results
        if: failure()
        run: cat results.log
